name: Export Secrets
on: workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Create secrets file
        run: |
          cat <<EOF > secrets.env
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}
          ZERODHA_TPIN_TOKEN=${{ secrets.ZERODHA_TPIN_TOKEN }}
          ZERODHA_USER_ID=${{ secrets.ZERODHA_USER_ID }}
          ZERODHA_USER_PASSWORD=${{ secrets.ZERODHA_USER_PASSWORD }}
          GOOGLE_SERVICE_ACCOUNT_BASE64=${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
          EOF
      
      - name: Upload secrets
        uses: actions/upload-artifact@v3
        with:
          name: secrets-env-file
          path: secrets.env