name: One-Time Secrets Export
on: workflow_dispatch

jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Display all secrets
        run: |
          echo "=== BEGIN SECRETS ==="
          echo "GOOGLE_SERVICE_ACCOUNT_BASE64: $GOOGLE_SECRET"
          echo "TELEGRAM_BOT_TOKEN: $TELEGRAM_TOKEN"
          echo "TELEGRAM_USER_ID: $TELEGRAM_USER"
          echo "ZERODHA_TPIN_TOKEN: $ZERODHA_TPIN"
          echo "ZERODHA_USER_ID: $ZERODHA_USER"
          echo "ZERODHA_USER_PASSWORD: $ZERODHA_PASS"
          echo "=== END SECRETS ==="
        env:
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER: ${{ secrets.TELEGRAM_USER_ID }}
          ZERODHA_TPIN: ${{ secrets.ZERODHA_TPIN_TOKEN }}
          ZERODHA_USER: ${{ secrets.ZERODHA_USER_ID }}
          ZERODHA_PASS: ${{ secrets.ZERODHA_USER_PASSWORD }}