name: Export All Secrets
on: 
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'EXPORT' to confirm"
        required: true
        default: "NO"

jobs:
  export:
    if: inputs.confirmation == 'EXPORT'
    runs-on: ubuntu-latest
    steps:
      - name: Create secrets file
        run: |
          cat <<EOF > all_secrets.env
          # GitHub Secrets Export - $(date)
          GOOGLE_SERVICE_ACCOUNT_BASE64='${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}'
          TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}'
          TELEGRAM_USER_ID='${{ secrets.TELEGRAM_USER_ID }}'
          ZERODHA_TPIN_TOKEN='${{ secrets.ZERODHA_TPIN_TOKEN }}'
          ZERODHA_USER_ID='${{ secrets.ZERODHA_USER_ID }}'
          ZERODHA_USER_PASSWORD='${{ secrets.ZERODHA_USER_PASSWORD }}'
          EOF
          
          # Create verification checksum
          sha256sum all_secrets.env > checksum.sha256

      - name: Upload secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets_export
          path: |
            all_secrets.env
            checksum.sha256
          retention-days: 1