name: Goldbees Trading Automation

on:
  schedule:
    # Runs at 8:00 AM IST (2:30 AM UTC) for buy
    - cron: '30 2 * * 1-5'
    # Runs at 8:01 AM IST (2:31 AM UTC) for sell
    - cron: '31 2 * * 1-5'
  workflow_dispatch:  # Manual trigger for both buy and sell

permissions:
  contents: read  # Only need read permission now

jobs:
  buy:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
      ZERODHA_USER_ID: ${{ secrets.ZERODHA_USER_ID }}
      ZERODHA_USER_PASSWORD: ${{ secrets.ZERODHA_USER_PASSWORD }}
      ZERODHA_TPIN_TOKEN: ${{ secrets.ZERODHA_TPIN_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
    steps:
      - name: Clear Jugaad Data Cache
        run: |
          rm -rf ~/.cache/nsehistory-stock
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install oauth2client PyDrive2

      - name: Run Buy Operation
        run: |
          python3 gold/gold_trading.py --buy

      - name: Verify Google Drive Log
        run: |
          echo "Buy operation completed. Logs stored in Google Drive."

  sell:
    runs-on: ubuntu-latest
    needs: buy
    if: always()  # Always run sell even if buy fails
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
      ZERODHA_USER_ID: ${{ secrets.ZERODHA_USER_ID }}
      ZERODHA_USER_PASSWORD: ${{ secrets.ZERODHA_USER_PASSWORD }}
      ZERODHA_TPIN_TOKEN: ${{ secrets.ZERODHA_TPIN_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
    steps:
      - name: Clear Jugaad Data Cache
        run: |
          rm -rf ~/.cache/nsehistory-stock
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install oauth2client PyDrive2

      - name: Run Sell Operation
        run: |
          python3 gold/gold_trading.py --sell

      - name: Verify Google Drive Log
        run: |
          echo "Sell operation completed. Logs stored in Google Drive."